class Contact {
  const Contact(
    this.name,
    this.role,
    this.address,
    this.phone,
    this.email,
    this.website,
  );

  final String name;
  final String role;
  final String address;
  final String phone;
  final String email;
  final String website;

  static const contacts = [
    Contact(
      'Bette Gracey',
      'Biostatistician IV',
      '1 Cherokee Parkway',
      '804-575-0381',
      'bgracey0@feed.pl',
      'utexas.edu',
    ),
    
    Contact(
      'Armenta Ross',
      'Programador',
      '1 Cherokee Parkway',
      '804-575-0381',
      'bgracey0@feed.pl',
      'utexas.edu',
    ),

    Contact(
      'Armenta Ross',
      'Programador',
      '1 Cherokee Parkway',
      '804-575-0381',
      'bgracey0@feed.pl',
      'utexas.edu',
    ),

    Contact(
      'Armenta Ross',
      'Programador',
      '1 Cherokee Parkway',
      '804-575-0381',
      'bgracey0@feed.pl',
      'utexas.edu',
    ),

    Contact(
      'Armenta Ross',
      'Programador',
      '1 Cherokee Parkway',
      '804-575-0381',
      'bgracey0@feed.pl',
      'utexas.edu',
    ),
    Contact(
      'Armenta Ross',
      'Programador',
      '1 Cherokee Parkway',
      '804-575-0381',
      'bgracey0@feed.pl',
      'utexas.edu',
    ),
    Contact(
      'Armenta Ross',
      'Programador',
      '1 Cherokee Parkway',
      '804-575-0381',
      'bgracey0@feed.pl',
      'utexas.edu',
    ),
    Contact(
      'Armenta Ross',
      'Programador',
      '1 Cherokee Parkway',
      '804-575-0381',
      'bgracey0@feed.pl',
      'utexas.edu',
    ),
    Contact(
      'Armenta Ross',
      'Programador',
      '1 Cherokee Parkway',
      '804-575-0381',
      'bgracey0@feed.pl',
      'utexas.edu',
    ),
    Contact(
      'Armenta Ross',
      'Programador',
      '1 Cherokee Parkway',
      '804-575-0381',
      'bgracey0@feed.pl',
      'utexas.edu',
    ),
    Contact(
      'Armenta Ross',
      'Programador',
      '1 Cherokee Parkway',
      '804-575-0381',
      'bgracey0@feed.pl',
      'utexas.edu',
    ),
    Contact(
      'Armenta Ross',
      'Programador',
      '1 Cherokee Parkway',
      '804-575-0381',
      'bgracey0@feed.pl',
      'utexas.edu',
    ),
    Contact(
      'Armenta Ross',
      'Programador',
      '1 Cherokee Parkway',
      '804-575-0381',
      'bgracey0@feed.pl',
      'utexas.edu',
    ),
    Contact(
      'Armenta Ross',
      'Programador',
      '1 Cherokee Parkway',
      '804-575-0381',
      'bgracey0@feed.pl',
      'utexas.edu',
    ),
    Contact(
      'Armenta Ross',
      'Programador',
      '1 Cherokee Parkway',
      '804-575-0381',
      'bgracey0@feed.pl',
      'utexas.edu',
    ),
    Contact(
      'Armenta Ross',
      'Programador',
      '1 Cherokee Parkway',
      '804-575-0381',
      'bgracey0@feed.pl',
      'utexas.edu',
    ),
    Contact(
      'Armenta Ross',
      'Programador',
      '1 Cherokee Parkway',
      '804-575-0381',
      'bgracey0@feed.pl',
      'utexas.edu',
    ),
    Contact(
      'Armenta Ross',
      'Programador',
      '1 Cherokee Parkway',
      '804-575-0381',
      'bgracey0@feed.pl',
      'utexas.edu',
    ),
    Contact(
      'Armenta Ross',
      'Programador',
      '1 Cherokee Parkway',
      '804-575-0381',
      'bgracey0@feed.pl',
      'utexas.edu',
    ),
    Contact(
      'Armenta Ross',
      'Programador',
      '1 Cherokee Parkway',
      '804-575-0381',
      'bgracey0@feed.pl',
      'utexas.edu',
    ),
    Contact(
      'Armenta Ross',
      'Programador',
      '1 Cherokee Parkway',
      '804-575-0381',
      'bgracey0@feed.pl',
      'utexas.edu',
    ),
    Contact(
      'Armenta Ross',
      'Programador',
      '1 Cherokee Parkway',
      '804-575-0381',
      'bgracey0@feed.pl',
      'utexas.edu',
    ),
    Contact(
      'Armenta Ross',
      'Programador',
      '1 Cherokee Parkway',
      '804-575-0381',
      'bgracey0@feed.pl',
      'utexas.edu',
    ),
    Contact(
      'Armenta Ross',
      'Programador',
      '1 Cherokee Parkway',
      '804-575-0381',
      'bgracey0@feed.pl',
      'utexas.edu',
    ),
    Contact(
      'Armenta Ross',
      'Programador',
      '1 Cherokee Parkway',
      '804-575-0381',
      'bgracey0@feed.pl',
      'utexas.edu',
    ),
    Contact(
      'Armenta Ross',
      'Programador',
      '1 Cherokee Parkway',
      '804-575-0381',
      'bgracey0@feed.pl',
      'utexas.edu',
    ),
    Contact(
      'Armenta Ross',
      'Programador',
      '1 Cherokee Parkway',
      '804-575-0381',
      'bgracey0@feed.pl',
      'utexas.edu',
    ),
    Contact(
      'Armenta Ross',
      'Programador',
      '1 Cherokee Parkway',
      '804-575-0381',
      'bgracey0@feed.pl',
      'utexas.edu',
    ),
    Contact(
      'Armenta Ross',
      'Programador',
      '1 Cherokee Parkway',
      '804-575-0381',
      'bgracey0@feed.pl',
      'utexas.edu',
    ),
    Contact(
      'Armenta Ross',
      'Programador',
      '1 Cherokee Parkway',
      '804-575-0381',
      'bgracey0@feed.pl',
      'utexas.edu',
    ),
    Contact(
      'Armenta Ross',
      'Programador',
      '1 Cherokee Parkway',
      '804-575-0381',
      'bgracey0@feed.pl',
      'utexas.edu',
    ),
    Contact(
      'Armenta Ross',
      'Programador',
      '1 Cherokee Parkway',
      '804-575-0381',
      'bgracey0@feed.pl',
      'utexas.edu',
    ),
    
  ];
}